### ISSUE TITLE
Redirect after oauth

### ISSUE THREAD

**Issue by Santana1053** [bolsunovskyi/freescout-oauth#5]
After signing in with oauth it just takes you to the homepage. Please make it so that it takes you to the page originally requested.

**Comment by bolsunovskyi** [comment]
@Santana1053 can you test fix for this issue in separate branch ? 
https://github.com/bolsunovskyi/freescout-oauth/tree/issue-5

**Comment by Santana1053** [comment]
Seems to be working for me. Thanks!
