### ISSUE TITLE
No scope passed in request

### ISSUE THREAD

**Issue by tiredofit** [bolsunovskyi/freescout-oauth#7]
I'm trying to use [LLNG](https://lemonldap-ng.org) to evaluate your plugin for OIDC.

When I attempt to test it out my authentication provider complains that no scope is being passed.
Do you understand why?

**Comment by bolsunovskyi** [comment]
Try to add scope to auth url in module settings, like this:
https:/example.com/oauth2/v2.0/authorize?scope=email+profile

**Comment by tiredofit** [comment]
Thanks. That did solve that problem and I'm sort of able to login.

Using an incognito window I am able to access my OIDC Provider, authenticate successfully and upon redirect it stalls out. When I refresh the page (in between the redirection from Auth Provider -> Freescout), it throws an error on my Auth side. If at that point I visit directly my Freescout site, it logs me in, provided I have an active user account in the system.

I also note, when I click the Logout button, my Auth provider requests authorization to provide claim details to the OIDC Provider.

**Comment by tiredofit** [comment]
I just had a few of my team members try on Firefox and Chrome, all seems to be well. Thanks for this! We were using a proxy styled authentication solution which relied on hacking away at the source code to pass REMOTE_USER in. This will be much more stable!
